using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShenmueDKSharp.Files.Models
{
    /// <summary>
    /// Wavefront OBJ format
    /// </summary>
    public class OBJ : BaseModel
    {
        public OBJ(BaseModel model)
        {
            model.CopyTo(this);
        }
        public OBJ(string filepath)
        {
            Read(filepath);
        }
        public OBJ(Stream stream)
        {
            Read(stream);
        }
        public OBJ(BinaryReader reader)
        {
            Read(reader);
        }

        public override void Read(Stream stream)
        {
            using (BinaryReader reader = new BinaryReader(stream))
            {
                Read(reader);
            }
        }

        public override void Write(Stream stream)
        {
            using (BinaryWriter writer = new BinaryWriter(stream))
            {
                Write(writer);
            }
        }

        public void Read(BinaryReader reader)
        {
            throw new NotImplementedException();
        }

        public void Write(BinaryWriter writer)
        {
            int totalVertices = 0;
            int objNum = 0;

            Console.WriteLine("# OBJ Generated by ShenmueDKSharp");

            foreach (ModelNode node in RootNode.GetAllNodes())
            {
                Matrix4 transformMatrix = node.GetTransformMatrix();

                foreach (MeshFace face in node.Faces)
                {
                    Console.WriteLine("# FaceVertCount: {0}", face.VertexIndices.Length);

                    //TODO: assign textures to groups
                    uint textureIndex = face.TextureIndex;
                    Texture texture = face.Material.Texture;

                    Vertex[] vertices = face.GetVertexArray(node);

                    for (int i = 0; i < vertices.Length; i++)
                    {
                        vertices[i].Position = Vector3.TransformPosition(vertices[i].Position, transformMatrix);
                    }

                    if (vertices[0].HasVertex())
                    {
                        Console.WriteLine("g TEST_{0}", objNum);

                        for (int i = 0; i < vertices.Length; i++)
                        {
                            Console.WriteLine("v {0:F6} {1:F6} {2:F6}", vertices[i].PosX, vertices[i].PosY, vertices[i].PosZ);
                        }
                    }

                    if (vertices[0].HasNormal())
                    {
                        for (int i = 0; i < vertices.Length; i++)
                        {
                            Console.WriteLine("vn {0:F6} {1:F6} {2:F6}", vertices[i].NormX, vertices[i].NormY, vertices[i].NormZ);
                        }
                    }

                    if (vertices[0].HasUV())
                    {
                        for (int i = 0; i < vertices.Length; i++)
                        {
                            Console.WriteLine("vt {0:F6} {1:F6}", vertices[i].U, vertices[i].V);
                        }
                    }

                    if (face.Type == MeshFace.PrimitiveType.Triangles)
                    {
                        for (int i = 1; i < face.VertexIndices.Length + 1; i += 3)
                        {
                            int index = i + totalVertices;
                            Console.WriteLine(GetVertexFormatString(vertices[i]), index, index + 1, index + 2);
                        }
                    }
                    else if (face.Type == MeshFace.PrimitiveType.TriangleStrip)
                    {
                        for (int i = 1; i < face.VertexIndices.Length - 1; i++)
                        {
                            int index = i + totalVertices;
                            if ((i & 1) == 1)
                            {
                                Console.WriteLine(GetVertexFormatString(vertices[i]), index, index + 1, index + 2);
                            }
                            else
                            {
                                Console.WriteLine(GetVertexFormatString(vertices[i]), index, index + 2, index + 1);
                            }
                        }
                    }
                    objNum++;
                    totalVertices += vertices.Length;
                }
            }

            Console.WriteLine("# Total Verts: {0}", totalVertices);
            //throw new NotImplementedException();
        }

    private string GetVertexFormatString(Vertex vertex)
        {
            if (vertex.HasVertex())
            {
                if (vertex.HasNormal())
                {
                    if (vertex.HasUV())
                    {
                        return "f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}";
                    }
                    else
                    {
                        return "f {0}//{0} {1}//{1} {2}//{2}";
                    }
                }
                else
                {
                    return "f {0} {1} {2}";
                }
            }
            return "";
        }
    }
}
