using ShenmueDKSharp.Files.Models._OBJ;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShenmueDKSharp.Files.Models
{
    /// <summary>
    /// Wavefront OBJ format
    /// </summary>
    public class OBJ : BaseModel
    {
        public static bool EnableBuffering = false;
        public override bool BufferingEnabled => EnableBuffering;

        public OBJ(BaseModel model)
        {
            model.CopyTo(this);
            FilePath = Path.ChangeExtension(model.FilePath, "obj");
        }
        public OBJ(string filepath)
        {
            Read(filepath);
        }
        public OBJ(Stream stream)
        {
            Read(stream);
        }
        public OBJ(BinaryReader reader)
        {
            Read(reader);
        }

        protected override void _Read(BinaryReader reader)
        {
            throw new NotImplementedException();
        }

        protected override void _Write(BinaryWriter writer)
        {
            int totalVertices = 0;
            int totalUVs = 0;
            int objNum = 0;

            MTL mtl = new MTL(this);
            if (String.IsNullOrEmpty(FilePath))
            {
                //TODO: Make this somehow better
                throw new ArgumentException("Filepath was not given.");
            }

            string mtlPath = "";
            string dir = Path.GetDirectoryName(FilePath);
            if (String.IsNullOrEmpty(dir) || dir == "\\" || Path.GetExtension(FilePath) == ".OBJ" || Path.GetExtension(FilePath) == ".obj")
            {
                mtlPath = Path.ChangeExtension(FilePath, ".mtl");
            }
            else
            {
                mtlPath = String.Format("{0}\\{1}", Path.GetDirectoryName(FilePath), Path.ChangeExtension(FilePath, ".mtl"));
            }
            mtl.Write(mtlPath);

            CultureInfo cultureInfo = new CultureInfo("en-GB");

            writer.WriteASCII("# OBJ Generated by ShenmueDKSharp\n");

            writer.WriteASCII(String.Format("mtllib {0}\n", Path.GetFileName(mtlPath)));

            foreach (ModelNode node in RootNode.GetAllNodes())
            {
                Matrix4 transformMatrix = node.GetTransformMatrix();

                bool faceUV = false;
                if (node.Faces.Count == 0) continue;
                Vertex[] vertices = MeshFace.GetVertexArrayFaces(node.Faces, node.Vertices);
                if (vertices.Length == 0) continue;

                writer.WriteASCII(String.Format("o obj_{0}\n", objNum));

                for (int i = 0; i < vertices.Length; i++)
                {
                    vertices[i].Position = Vector3.TransformPosition(vertices[i].Position, transformMatrix);
                }

                if (vertices[0].HasVertex())
                {
                    for (int i = 0; i < vertices.Length; i++)
                    {
                        writer.WriteASCII(String.Format(cultureInfo, "v {0:F6} {1:F6} {2:F6}\n", vertices[i].PosX, vertices[i].PosY, vertices[i].PosZ));
                    }
                }

                if (node.Faces[0].UVs.Count == 0)
                {
                    if (vertices[0].HasUV())
                    {
                        for (int i = 0; i < vertices.Length; i++)
                        {
                            writer.WriteASCII(String.Format(cultureInfo, "vt {0:F6} {1:F6}\n", vertices[i].U, vertices[i].V));
                        }
                    }
                }
                else
                {
                    faceUV = true;
                    foreach (MeshFace face in node.Faces)
                    {
                        foreach (Vector2 uv in face.UVs)
                        {
                            writer.WriteASCII(String.Format(cultureInfo, "vt {0:F6} {1:F6}\n", uv.X, uv.Y));
                        }
                    }
                }

                if (vertices[0].HasNormal())
                {
                    for (int i = 0; i < vertices.Length; i++)
                    {
                        writer.WriteASCII(String.Format(cultureInfo, "vn {0:F6} {1:F6} {2:F6}\n", vertices[i].NormX, vertices[i].NormY, vertices[i].NormZ));
                    }
                }

                foreach (MeshFace face in node.Faces)
                {
                    uint textureIndex = face.TextureIndex;
                    Texture texture = face.Material.Texture;

                    writer.WriteASCII(String.Format("usemtl mat_{0}\n", textureIndex));
                    writer.WriteASCII("s 1\n");

                    if (faceUV)
                    {
                        if (face.Type == MeshFace.PrimitiveType.TriangleStrip)
                        {

                            for (int i = 0; i < face.VertexIndices.Length - 2; i++)
                            {
                                int index1 = face.VertexIndices[i] + totalVertices + 1;
                                int index2 = face.VertexIndices[i + 1] + totalVertices + 1;
                                int index3 = face.VertexIndices[i + 2] + totalVertices + 1;

                                int uv1 = i + 1 + totalUVs;
                                int uv2 = i + 2 + totalUVs;
                                int uv3 = i + 3 + totalUVs;

                                if ((i & 1) == 1)
                                {
                                    writer.WriteASCII(String.Format(GetVertexFormatStringUV(vertices[face.VertexIndices[i]]), index1, index2, index3, uv1, uv2, uv3));
                                }
                                else
                                {
                                    writer.WriteASCII(String.Format(GetVertexFormatStringUV(vertices[face.VertexIndices[i]]), index1, index3, index2, uv1, uv3, uv2));
                                }
                            }
                        }
                        totalUVs += face.UVs.Count;
                    }
                    else
                    {
                        if (face.Type == MeshFace.PrimitiveType.Triangles)
                        {
                            for (int i = 0; i < face.VertexIndices.Length - 2; i += 3)
                            {
                                int index1 = face.VertexIndices[i] + totalVertices + 1;
                                int index2 = face.VertexIndices[i + 1] + totalVertices + 1;
                                int index3 = face.VertexIndices[i + 2] + totalVertices + 1;
                                writer.WriteASCII(String.Format(GetVertexFormatString(vertices[face.VertexIndices[i]]), index1, index2, index3));
                            }
                        }
                        else if (face.Type == MeshFace.PrimitiveType.TriangleStrip)
                        {
                            for (int i = 0; i < face.VertexIndices.Length - 2; i++)
                            {
                                int index1 = face.VertexIndices[i] + totalVertices + 1;
                                int index2 = face.VertexIndices[i + 1] + totalVertices + 1;
                                int index3 = face.VertexIndices[i + 2] + totalVertices + 1;
                                if ((i & 1) == 1)
                                {
                                    writer.WriteASCII(String.Format(GetVertexFormatString(vertices[face.VertexIndices[i]]), index1, index2, index3));
                                }
                                else
                                {
                                    writer.WriteASCII(String.Format(GetVertexFormatString(vertices[face.VertexIndices[i]]), index1, index3, index2));
                                }
                            }
                        }
                    }
                }
                objNum++;
                totalVertices += vertices.Length;
            }
            writer.WriteASCII(String.Format("# Total Verts: {0}\n", totalVertices));
        }

        private string GetVertexFormatStringUV(Vertex vertex)
        {
            if (vertex.HasVertex())
            {
                if (vertex.HasNormal())
                {
                    if (vertex.HasUV())
                    {
                        return "f {0}/{3}/{0} {1}/{4}/{1} {2}/{5}/{2}\n";
                    }
                    else
                    {
                        return "f {0}//{3} {1}//{4} {2}//{5}\n";
                    }
                }
                else
                {
                    return "f {0} {1} {2}\n";
                }
            }
            return "";
        }

        private string GetVertexFormatString(Vertex vertex)
        {
            if (vertex.HasVertex())
            {
                if (vertex.HasNormal())
                {
                    if (vertex.HasUV())
                    {
                        return "f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n";
                    }
                    else
                    {
                        return "f {0}//{0} {1}//{1} {2}//{2}\n";
                    }
                }
                else
                {
                    return "f {0} {1} {2}\n";
                }
            }
            return "";
        }
    }
}
